### ISSUE TITLE
Pipe client output directly to file

### ISSUE THREAD

**Issue by holiman** [ethereum/evmlab#82]
Sometimes, the fuzzer hangs. 
A recent example happened when the a hung/dead parity process, when executed manually, totalled 4M. This probably overflows some socket receiving buffer, and we don't read it quickly enough, so things go haywire. 

New idea: instead of reading the output from the process, we should instead pipe it directly to a file. `/bin/sh -c "parity x y z" &> file.log`, and the `file.log` should be on a volume-mount from the host, so we read it directly from the host filesystem afterwards.

This is how we start parity now: https://github.com/ethereum/evmlab/blob/master/utilities/fuzzer.py#L336
```python


def startGeth(test):
    cmd = ["evm","--json","--nomemory","statetest","/testfiles/%s" % os.path.basename(test.filename())]
    return execInDocker("geth", cmd, stdout = False)
    

def startParity(test):
    cmd = ["/bin/sh","-c","/parity-evm state-test --std-json /testfiles/%s 1>&2" % os.path.basename(test.filename())]
    return execInDocker("parity", cmd)

```

We later store the trace: 
```
        full_trace = proc_info["output"]()
        test.storeTrace(client_name, full_trace,proc_info['cmd'])
```
So we could skip that step if we pipe it to file immediately.

**Comment by holiman** [comment]
Some problems on prod
```
2018-10-09 12:00:42,646 - INFO - Starting processes for ['geth', 'parity'] on test DEFAULT-Tue_12_00_41-17761-0
2018-10-09 12:00:42,666 - INFO - Starting processes for ['geth', 'parity'] on test DEFAULT-Tue_12_00_41-17761-1
2018-10-09 12:00:42,857 - INFO - Processed 6 steps for geth on test DEFAULT-Tue_12_00_41-17761-0, wtime: 178.87 ms, pTime:0.36 ms
Traceback (most recent call last):
  File "utilities/fuzzerweb.py", line 59, in <module>
    main()
  File "utilities/fuzzerweb.py", line 55, in main
    f.startFuzzing()
  File "/datadrive/evmlab/utilities/fuzzer.py", line 520, in startFuzzing
    __end_previous_test()
  File "/datadrive/evmlab/utilities/fuzzer.py", line 486, in __end_previous_test
    data = end_processes(previous_test)
  File "/datadrive/evmlab/utilities/fuzzer.py", line 425, in end_processes
    with open(test.tempTraceLocation(client_name)) as output:
FileNotFoundError: [Errno 2] No such file or directory: '/datadrive/evmlabtemp/logs/DEFAULT-Tue_12_00_41-17761-0-parity.trace.log'
```

**Comment by holiman** [comment]
Ah, the parity user process can't write to the file
```
/bin/sh: can't create /logs/DEFAULT-Tue_12_05_45-19131-0-parity.trace.log: Permission denied
```

**Comment by holiman** [comment]
After a chmod, this now bumped it up to 5.5 tests per second, which is a nice boost (although I get higher speeds locally)
